In [2]:
import pandas as pd
import numpy as np

In [3]:
vehicles = ["Car","Bus","Bicycle","Bike"]

In [20]:
vehicle = ["Car","Bus","Bicycle","Bike","Bicycle","Bike","Bicycle","Bike","Bicycle","Bicycle"]

labels, unique_vehicle = pd.factorize(vehicle)
labels = labels + 1

# print("Labels:", labels)
# print("Unique values:", uniques)

binary_data = [format(i, '03b') for i in labels]

matrix = np.array([list(map(int, list(b))) for b in binary_data])

print(f"Vechicles {unique_vehicle}")
print(f"Binary {matrix}")



Vechicles ['Car' 'Bus' 'Bicycle' 'Bike']
Binary [[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [1 0 0]
 [0 1 1]
 [0 1 1]]


C:\Users\hp\AppData\Local\Temp\ipykernel_13372\2421595603.py:3: FutureWarning: factorize with argument that is not not a Series, Index, ExtensionArray, or np.ndarray is deprecated and will raise in a future version.
  labels, unique_vehicle = pd.factorize(vehicle)


In [26]:
first_names = ["Rohit","Aman","Priya","Neha","Arjun",
               "Kiran","Sonal","Rahul","Anjali","Vikas",
               "Meena","Suresh","Pooja","Deepak","Riya",
               "Aakash","Nisha","Varun","Sneha","Tarun",
               "Isha","Manoj","Kavya","Ramesh","Divya",
               "Harsh","Komal","Aditya","Simran","Yash"]

last_names = ["Sharma","Verma","Singh","Kapoor","Mehta",
              "Yadav","Gupta","Das","Kumar","Pandey",
              "Rao","Joshi","Patel","Nair","Chopra",
              "Saxena","Malhotra","Bose","Trivedi","Shah",
              "Tiwari","Bhat","Gill","Chaudhary","Reddy",
              "Sinha","Arora","Ghosh","Kulkarni","Mishra"]

states = ["Jharkhand","Bihar","Delhi","Maharashtra","UP"]

data = {
    "First_Name": first_names,
    "Last_Name": last_names,
    "State": np.random.choice(states, 30),
    "Owning_Vehicle": np.random.choice(vehicles, 30)
}

df = pd.DataFrame(data)

print("Original Dataset:\n")
# print(df)
# df

# all_data = pd.

labels, unique_vehicle = pd.factorize(df['Owning_Vehicle'])
labels = labels + 1

# print("Labels:", labels)
# print("Unique values:", uniques)

binary_data = [format(i, '03b') for i in labels]

matrix = np.array([list(map(int, list(b))) for b in binary_data])

print(f"Unique Vehicles {unique_vehicle}")
print(f"All Data {matrix}")

Original Dataset:

Unique Vehicles Index(['Bus', 'Bicycle', 'Car', 'Bike'], dtype='object')
All Data [[0 0 1]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [0 1 1]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 1 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]
 [0 1 1]
 [0 1 0]
 [0 1 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]]


In [14]:
labels, uniques = pd.factorize(df["Owning_Vehicle"])

df["Vehicle_Label"] = labels

print("\nEncoded Dataset:\n")
print(df)

print("\nUnique Vehicle Categories:")
print(uniques)



Encoded Dataset:

   First_Name  Last_Name        State Owning_Vehicle  Vehicle_Label  Owning_Vehicle_Ordinal
0       Rohit     Sharma           UP            Bus              0                       1
1        Aman      Verma    Jharkhand            Bus              0                       1
2       Priya      Singh           UP            Bus              0                       1
3        Neha     Kapoor  Maharashtra            Car              1                       0
4       Arjun      Mehta        Bihar            Car              1                       0
5       Kiran      Yadav  Maharashtra            Car              1                       0
6       Sonal      Gupta        Bihar           Bike              2                       3
7       Rahul        Das        Bihar        Bicycle              3                       2
8      Anjali      Kumar        Delhi            Car              1                       0
9       Vikas     Pandey    Jharkhand            Car         

In [7]:
df_encoded = pd.get_dummies(df, columns=["Owning_Vehicle"], dtype=int)


pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False) 


print("\nAfter One-Hot Encoding:\n")
print(df_encoded)



After One-Hot Encoding:

   First_Name  Last_Name        State  Vehicle_Label  Owning_Vehicle_Bicycle  Owning_Vehicle_Bike  Owning_Vehicle_Bus  Owning_Vehicle_Car
0       Rohit     Sharma           UP              0                       0                    0                   1                   0
1        Aman      Verma    Jharkhand              0                       0                    0                   1                   0
2       Priya      Singh           UP              0                       0                    0                   1                   0
3        Neha     Kapoor  Maharashtra              1                       0                    0                   0                   1
4       Arjun      Mehta        Bihar              1                       0                    0                   0                   1
5       Kiran      Yadav  Maharashtra              1                       0                    0                   0                   1
6       

In [8]:
df["Owning_Vehicle_Ordinal"] = pd.Categorical(
    df["Owning_Vehicle"],
    categories=vehicles,
    ordered=True
).codes

# print(df.head())
df

,First_Name,Last_Name,State,Owning_Vehicle,Vehicle_Label,Owning_Vehicle_Ordinal
0,Rohit,Sharma,UP,Bus,0,1
1,Aman,Verma,Jharkhand,Bus,0,1
2,Priya,Singh,UP,Bus,0,1
3,Neha,Kapoor,Maharashtra,Car,1,0
4,Arjun,Mehta,Bihar,Car,1,0
5,Kiran,Yadav,Maharashtra,Car,1,0
6,Sonal,Gupta,Bihar,Bike,2,3
7,Rahul,Das,Bihar,Bicycle,3,2
8,Anjali,Kumar,Delhi,Car,1,0
9,Vikas,Pandey,Jharkhand,Car,1,0


KeyError: 'Owning_Vehical'