**Categorical Encoding** is the process of converting text-based or categorical data into numerical values so that a machine learning model can process the information without losing its meaning.

**categorical data** represents characteristics or qualities. Unlike numerical data, which tells you "how much" or "how many," categorical data tells you "what kind."
categorical data is data that describes "groups" or "qualities" rather than "quantities."

It consists of discrete groups or "labels" that describe an attribute of the subject you are studying.

**Why does Categorical Data need Encoding?**

Think of a computer like a calculator. A calculator is brilliant at math, but if you type the word "Apple" into it and hit the plus sign, it will just give you an error. It has no idea what an "Apple" is because it only speaks the language of numbers.
**Categorical Encoding** is the "translator" that turns words (categories) into numbers so the computer can do its math.

###**Types of Categorical Data**

**1. Nominal Data (No Order)**

The word "Nominal" comes from "Name." This is data where the categories are just labels or names. There is no "top" or "bottom," and one category isn't "better" than the other.

"Easy Rule: You cannot rank them in a logical list."

Examples:

Eye Color: Brown, Blue, Green (One isn't "higher" than the other).

Gender: Male, Female, Non-binary.

Pet Type: Dog, Cat, Hamster, Bird.

City: New York, London, Tokyo.

**2. Ordinal Data (Has a Natural Order)**

The word "Ordinal" sounds like "Order." These are categories where the sequence or rank matters. While you still can't do math with them (you can't add "Silver" + "Gold"), you know exactly which one comes first, second, or third.

"Easy Rule: You can put them in a line from "low to high" or "first to last."

Examples:

Size: Small, Medium, Large.

Happiness: Sad, Neutral, Happy.

Education: High School, College, Masters, PhD.

Race Results: 1st Place, 2nd Place, 3rd Place.


---



Nominal question: "Which type of milk do you prefer?"

(Options: Whole, Oat, Soy, Almond). One isn't "higher" than the other.

Ordinal question: "How hot do you like your coffee?"

(Options: Lukewarm, Warm, Hot, Extra Hot). There is a clear progression of temperature.


---



**Example**

$$\begin{array}{|2|2|2|}
\hline
\textbf{Data Type} & \textbf{Nominal (No Order)} & \textbf{Ordinal (Ordered)} \\ \hline
\textbf{Categorical} & \text{Cuisine Type: Italian, Mexican,} & \text{Service Quality: Poor, Fair,} \\
\text{(Words/Labels)} & \text{Thai, Indian. (Labels only)} & \text{Good, Excellent. (Ranked)} \\ \hline
\textbf{Numerical} & \text{Table Number: 5, 12, 24.} & \text{Star Rating: 1-star, 2-stars,} \\
\text{(Numbers)} & \text{(Numbers act as labels)} & \text{3-stars. (Mathematical rank)} \\ \hline
\end{array}$$

###**Why Care About Proper Encoding**

**1. Preventing "Fake Math" :**

If you use simple Label Encoding (1, 2, 3) on Nominal data like "City" (New York=1, Paris=2, Tokyo=3), the model will treat those numbers mathematically.

a. The Error: The model will think $Tokyo (3) > New York (1)$.

b.The Consequence: It might calculate that $New York + Paris = Tokyo$. Since there is no actual relationship between these cities, your model’s "math" is based on a lie.

**2. Handling the "Ordinal Signal"**

On the flip side, if you have Ordinal data (Small, Medium, Large) and you use One-Hot Encoding (creating separate 0/1 columns for each), you actually lose information.

a. The Loss: The model no longer sees the progression. It won't know that "Medium" is halfway between "Small" and "Large.

b. "The Benefit of Proper Encoding: Using $1, 2, 3$ here tells the model that there is a steady increase, which helps it make much more accurate predictions.

**3. The "Curse of Dimensionality"**

If you have a category with 100 different values (like "Zip Code") and you use One-Hot Encoding, you just added 100 new columns to your dataset.

a. The Problem: Too many columns make the model incredibly slow and prone to overfitting (where the model memorizes the data instead of learning from it).

b. The Solution: Proper encoding (like Binary or Target Encoding) keeps the data slim and manageable.

**4. Improving "Distance" Calculations**

Many algorithms (like K-Nearest Neighbors or SVMs) calculate the "distance" between points to see how similar they are.

a. If you encode "Red" as 1 and "Yellow" as 10, the model thinks they are "far apart."

b. If you use One-Hot Encoding, the distance between any two colors is exactly the same, which is a much more accurate representation of the data.

###**Encoding Techniques**

**1. Label Encoding**

Label Encoding is a way to convert words (categories) into numbers so that a machine learning model can understand them.

This is the simplest form. You assign each category a unique number (0, 1, 2, 3...).

Best for: Ordinal Data (where order matters).

The Logic: It keeps the "rank" alive.

Example: Education Level.High School $\rightarrow$ 0Bachelor's $\rightarrow$ 1Master's $\rightarrow$ 2PhD $\rightarrow$ 3

In [ ]:
import numpy as np


data = np.array(['Small', 'Large', 'Medium', 'Small', 'Large'])

# Step 1: Find the unique labels
# This also sorts them alphabetically: ['Large', 'Medium', 'Small']
unique_labels = np.unique(data)

# Step 2: Map the labels to their numeric index
# return_inverse=True gives us the integer version automatically
unique_labels, encoded_values = np.unique(data, return_inverse=True)

print(f"Original Data: {data}")
print(f"Unique Labels (Alphabetical): {unique_labels}")
print(f"Encoded Values: {encoded_values}")

Original Data: ['Small' 'Large' 'Medium' 'Small' 'Large']
Unique Labels (Alphabetical): ['Large' 'Medium' 'Small']
Encoded Values: [2 0 1 2 0]


np.unique():
1. Filters ours duplicates(it keeps only one instance of every value.
2. Sorts them(its returns the labels in increasing order(alphabetical for strings, numerical for numbers).


When to Use It

 (The "Ordinal" Rule)Label Encoding is best used for Ordinal Data (where the order matters). Because the numbers follow a sequence ($0 < 1 < 2$), the computer can "understand" that Medium is greater than Small.

In [ ]:
import pandas as pd
df = pd.read_csv("/content/sample_data/Book9.csv")
print(df)

       Category  Label Logical Order
0      Beginner      0        Lowest
1  Intermediate      1        Middle
2        Expert      2       Highest


**2. One-Hot Encoding**

One-Hot Encoding creates a new binary column for each category in a categorical variable.
One-Hot Encoding splits that one column into three new ones. Only one column can be "hot" (set to $1$) at a time.

Step 1: Identify your Nominal Categories

First, look at your data and identify the unique values. In our case, we have three distinct categories. Note that there is no logical order (Green isn't "higher" than Red).

Categories: {Red, Blue, Green}

Step 2: Create a New Column for Every Category

For every unique value found in Step 1, create a brand-new column in your dataset. If you had 3 colors, your table expands by 3 columns.

Step 3: Assign Binary Values (The "1" and "0" Logic)

For each row, look at the original value and place a 1 in the corresponding new column and a 0 in all others.

If both are 0, the model knows the color is Red.

In [ ]:
import numpy as np


colors = np.array(['Red', 'Blue', 'Green', 'Red'])

# 2. Identify the unique categories
# unique = ['Blue', 'Green', 'Red']
unique_colors = np.unique(colors)

# 3. Use an Identity Matrix to map the categories
# This creates a grid of 0s with 1s on the diagonal
encoding_map = np.eye(len(unique_colors)) #identity matrix

# 4. Map the original colors to their corresponding row in the identity matrix
# 'Blue' gets row 0, 'Green' gets row 1, 'Red' gets row 2
indices = np.searchsorted(unique_colors, colors)
one_hot = encoding_map[indices]

print("One-Hot Encoded Matrix:")
print(one_hot)

One-Hot Encoded Matrix:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import pandas as pd

# 1. Create sample data
data = {'Color': ['Red', 'Blue', 'Green', 'Red']}
df = pd.DataFrame(data)

# 2. Apply One-Hot Encoding
encoded_df = pd.get_dummies(df, columns=['Color']) # itconverts categorical variables into a format the computer can digest.

print(encoded_df)

   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True


**3.Binary Encoding**

Binary encoding is a "middle ground" between Label Encoding and One-Hot Encoding. It’s designed to handle categories with many unique values without making your dataset too wide or confusing the model with arbitrary ranks.

Think of it as encoding your labels into "Secret Spy Code" (Binary numbers).

**How it Works**

 (The 3-Step Process)

Label Encoding: Assign each category a unique integer (1, 2, 3...).

Binary Conversion: Convert those integers into binary numbers (e.g., 3 becomes 011).

Splitting: Split the digits of the binary number into separate columns.

**Why use it?**

Saves Space: If you have 100 cities, One-Hot Encoding creates 100 columns. Binary Encoding only creates 7 columns (because $2^7 = 128$).

Less Bias: Unlike Label Encoding, the model doesn't just see a single number like "100," which reduces the risk of the model thinking one category is "larger" than another.

The Simple Concept
Think of it like a secret code. Instead of giving every category its own column (One-Hot), we give every category a unique binary number (like 01, 10, 11) and split those digits into columns.

If you have 8 different categories:One-Hot Encoding would need 8 columns.Binary Encoding would only need 3 columns (because $2^3 = 8$).

One-Hot Style:

Every color gets its own "light switch."

Red: [1, 0, 0, 0]

Blue: [0, 1, 0, 0]

Green: [0, 0, 1, 0]

Yellow: [0, 0, 0, 1]

Binary Style:

Each color gets a binary "ID number.

"Red $\rightarrow$ 01 $\rightarrow$ [0, 1]

Blue $\rightarrow$ 10 $\rightarrow$ [1, 0]

Green $\rightarrow$ 11 $\rightarrow$ [1, 1]

Yellow $\rightarrow$ 100 $\rightarrow$ [1, 0, 0]

(Wait, binary encoding usually pads with zeros to keep column length equal, so it would look like [0,0,1], [0,1,0], etc.)

In [ ]:
import pandas as pd
df = pd.read_csv("/content/excel.csv")
print(df)

       City  Label  Binary Code  Column 1  Column 2  Column 3
0  New York      1            1         0         0         1
1     Paris      2           10         0         1         0
2     Tokyo      3           11         0         1         1
3    London      4          100         1         0         0
4      Rome      5          101         1         0         1


In [ ]:
import numpy as np

# 1. Categorical data
cities = np.array(['New York', 'Paris', 'Tokyo', 'London'])

# 2. Get Label Encoded values (1, 2, 3, 4)
unique_cities, labels = np.unique(cities, return_inverse=True)
labels = labels + 1 # Start from 1 for cleaner binary

# 3. Convert to Binary Strings and split into columns
# We use 3 bits because we have 4 categories
binary_data = [format(i, '03b') for i in labels] #
matrix = np.array([list(map(int, list(b))) for b in binary_data])

print("Cities:", cities)
print("Binary Matrix:\n", matrix)

Cities: ['New York' 'Paris' 'Tokyo' 'London']
Binary Matrix:
 [[0 1 0]
 [0 1 1]
 [1 0 0]
 [0 0 1]]


**4. Target Encoding**

Target Encoding (also known as Mean Encoding) is a clever way to turn text into numbers by using the average of the target variable for each category.

Instead of using arbitrary IDs (Label Encoding) or expanding columns (One-Hot Encoding), you look at the "goal" (the target) and calculate the average result for that specific group.

**Why use it?**

a. No extra columns: It keeps your dataset slim (unlike One-Hot Encoding).

b. Stronger correlation: It creates a direct mathematical link between your feature (Neighborhood) and your target (Price).

c. Captures patterns: It handles high-cardinality data (like zip codes or cities) beautifully.

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Date': ['03-25', '03-26', '03-27', '03-28', '03-29', '03-30', '03-31', '04-01', '04-02', '04-03', '04-04', '04-05'],
    'Weekday': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Month': ['Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Apr', 'Apr', 'Apr', 'Apr', 'Apr'],
    'Temperature': ['High', 'Low', 'High', 'Extreme', 'Low', 'High', 'High', 'Low', 'High', 'Extreme', 'High', 'Low'],
    'Humidity': ['Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Humid', 'Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Dry'],
    'Wind': ['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes'],
    'Outlook': ['sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'sunny', 'overcast', 'sunny', 'rainy'],
    'Crowdedness': [85, 30, 65, 45, 25, 90, 95, 35, 70, 50, 80, 45]
}

df = pd.DataFrame(data)
print(df)

     Date Weekday Month Temperature Humidity Wind   Outlook  Crowdedness
0   03-25     Mon   Mar        High      Dry   No     sunny           85
1   03-26     Tue   Mar         Low    Humid  Yes     rainy           30
2   03-27     Wed   Mar        High      Dry  Yes  overcast           65
3   03-28     Thu   Mar     Extreme      Dry  Yes     sunny           45
4   03-29     Fri   Mar         Low    Humid   No     rainy           25
5   03-30     Sat   Mar        High    Humid   No  overcast           90
6   03-31     Sun   Mar        High      Dry  Yes     sunny           95
7   04-01     Mon   Apr         Low    Humid   No     rainy           35
8   04-02     Tue   Apr        High      Dry  Yes     sunny           70
9   04-03     Wed   Apr     Extreme      Dry  Yes  overcast           50
10  04-04     Thu   Apr        High    Humid   No     sunny           80
11  04-05     Fri   Apr         Low      Dry  Yes     rainy           45


In [ ]:
df['Humidity_target'] = df.groupby('Humidity')['Crowdedness'].transform('mean')
print(df)

     Date Weekday Month Temperature Humidity Wind   Outlook  Crowdedness  \
0   03-25     Mon   Mar        High      Dry   No     sunny           85   
1   03-26     Tue   Mar         Low    Humid  Yes     rainy           30   
2   03-27     Wed   Mar        High      Dry  Yes  overcast           65   
3   03-28     Thu   Mar     Extreme      Dry  Yes     sunny           45   
4   03-29     Fri   Mar         Low    Humid   No     rainy           25   
5   03-30     Sat   Mar        High    Humid   No  overcast           90   
6   03-31     Sun   Mar        High      Dry  Yes     sunny           95   
7   04-01     Mon   Apr         Low    Humid   No     rainy           35   
8   04-02     Tue   Apr        High      Dry  Yes     sunny           70   
9   04-03     Wed   Apr     Extreme      Dry  Yes  overcast           50   
10  04-04     Thu   Apr        High    Humid   No     sunny           80   
11  04-05     Fri   Apr         Low      Dry  Yes     rainy           45   

    Humidit

df['Humidity_target']

This selects (or creates) a column called Humidity_target in the DataFrame df.

If the column doesn’t exist, it will be created.

df.groupby('Humidity')

This groups the DataFrame by unique values in the Humidity column.

All rows with the same humidity value are placed into the same group.


['Crowdedness']

After grouping, this selects only the Crowdedness column within each humidity group.

So now we’re working with crowdedness values inside each humidity level.


.transform('mean')

This calculates the mean (average) of Crowdedness for each Humidity group.

Important:

transform() returns a value for every original row, not just one value per group.

It “broadcasts” the group mean back to each row in that group.

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Book4.csv")
print(df)

  Neighborhood  House Sold? (Target)  Calculation  Target Encoded Value
0     Brooklyn                     1  (1+1+0) / 3                  0.66
1     Brooklyn                     1          NaN                  0.66
2     Brooklyn                     0          NaN                  0.66
3       Queens                     0    (0+0) / 2                  0.00
4       Queens                     0          NaN                  0.00


**5. Ordinal Encoding**

Ordinal Encoding is a specific type of Label Encoding used when your categories have a natural order or rank.

Unlike "Color" (where Red isn't "higher" than Blue), Ordinal data follows a clear sequence, such as sizes, satisfaction levels, or education stages. In Ordinal Encoding, we manually assign numbers that preserve this rank.

The Scenario: Coffee Cup SizesImagine you are analyzing data for a coffee shop. The cup sizes are Small, Medium, and Large.

If you use standard Label Encoding, a computer might assign them randomly based on alphabetical order ($Large=0, Medium=1, Small=2$). This is bad because it tells the model that Large is "less than" Small.

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Book5.csv")
print(df)

  Cup Size      Rank/Order  Encoded Value
0    Small  1st (Smallest)              0
1   Medium             2nd              1
2    Large   3rd (Largest)              2


In [ ]:
import pandas as pd
import numpy as np

data = {
    'Date': ['03-25', '03-26', '03-27', '03-28', '03-29', '03-30', '03-31', '04-01', '04-02', '04-03', '04-04', '04-05'],
    'Weekday': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Month': ['Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Apr', 'Apr', 'Apr', 'Apr', 'Apr'],
    'Temperature': ['High', 'Low', 'High', 'Extreme', 'Low', 'High', 'High', 'Low', 'High', 'Extreme', 'High', 'Low'],
    'Humidity': ['Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Humid', 'Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Dry'],
    'Wind': ['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes'],
    'Outlook': ['sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'sunny', 'overcast', 'sunny', 'rainy'],
    'Crowdedness': [85, 30, 65, 45, 25, 90, 95, 35, 70, 50, 80, 45]
}

df = pd.DataFrame(data)
#print(df)
temp_order = {'Low': 1, 'High': 2, 'Extreme': 3}
df['Temperature_ordinal'] = df['Temperature'].map(temp_order)
print(df)

     Date Weekday Month Temperature Humidity Wind   Outlook  Crowdedness  \
0   03-25     Mon   Mar        High      Dry   No     sunny           85   
1   03-26     Tue   Mar         Low    Humid  Yes     rainy           30   
2   03-27     Wed   Mar        High      Dry  Yes  overcast           65   
3   03-28     Thu   Mar     Extreme      Dry  Yes     sunny           45   
4   03-29     Fri   Mar         Low    Humid   No     rainy           25   
5   03-30     Sat   Mar        High    Humid   No  overcast           90   
6   03-31     Sun   Mar        High      Dry  Yes     sunny           95   
7   04-01     Mon   Apr         Low    Humid   No     rainy           35   
8   04-02     Tue   Apr        High      Dry  Yes     sunny           70   
9   04-03     Wed   Apr     Extreme      Dry  Yes  overcast           50   
10  04-04     Thu   Apr        High    Humid   No     sunny           80   
11  04-05     Fri   Apr         Low      Dry  Yes     rainy           45   

    Tempera

temp_order = {'Low': 1, 'High': 2, 'Extreme': 3}

This creates a dictionary in Python.

'Low' → 1

'High' → 2

'Extreme' → 3

So you're defining a numerical order for temperature categories.

This is useful because:

'Low', 'High', 'Extreme' are categorical values

Machine learning models need numbers

You want to preserve order (ordinal relationship)


---


df['Temperature_ordinal'] = ...

This creates a new column called Temperature_ordinal in your DataFrame.

The result of the mapping operation will be stored here.


---



df['Temperature']

This selects the Temperature column from the DataFrame.



---


.map(temp_order)

.map() replaces each value using the dictionary.

It works like this:

If value = 'Low' → replace with 1

If value = 'High' → replace with 2

If value = 'Extreme' → replace with 3



###**Cyclic Encoding**

Cyclic Encoding is a clever way to handle data that repeats in a cycle, like time, days of the week, or months of the year.

The problem with standard encoding (like 0 to 23 for hours) is that it tells the computer that Hour 23 and Hour 0 are very far apart, when in reality, they are only one hour apart! Cyclic encoding uses trigonometry (Sine and Cosine) to wrap the numbers around into a circle so that the end meets the beginning.

The Concept: The "Clock" ProblemImagine the hours of a day. If we use numbers 0–23:

a. Distance between 11 PM (23) and 12 AM (0): The computer thinks the distance is 23.

b. Actual Distance: The distance is only 1.

To fix this, we project the time onto a circle. Every time point gets two new coordinates: Sine ($x$) and Cosine ($y$).

Cyclic Encoding/Transformation transforms a cyclical categorical variable into two numerical features that preserve the variable’s cyclical nature. It typically uses sine and cosine transformations to represent the cyclical pattern. For example, for the column “Month” we’d make it numerical first (1–12) then create two new features:



Month_cos = cos(2 π (m — 1) / 12)

Month_sin = sin(2 π (m — 1) / 12)

where m is a number from 1 to 12 representing January to December.

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Date': ['03-25', '03-26', '03-27', '03-28', '03-29', '03-30', '03-31', '04-01', '04-02', '04-03', '04-04', '04-05'],
    'Weekday': ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
    'Month': ['Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Mar', 'Apr', 'Apr', 'Apr', 'Apr', 'Apr'],
    'Temperature': ['High', 'Low', 'High', 'Extreme', 'Low', 'High', 'High', 'Low', 'High', 'Extreme', 'High', 'Low'],
    'Humidity': ['Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Humid', 'Dry', 'Humid', 'Dry', 'Dry', 'Humid', 'Dry'],
    'Wind': ['No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'Yes'],
    'Outlook': ['sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'overcast', 'sunny', 'rainy', 'sunny', 'overcast', 'sunny', 'rainy'],
    'Crowdedness': [85, 30, 65, 45, 25, 90, 95, 35, 70, 50, 80, 45]
}

df = pd.DataFrame(data)
#print(df)
month_order = {'Jan': 1, 'Feb': 2, 'Mar': 3, 'Apr': 4, 'May': 5, 'Jun': 6,
               'Jul': 7, 'Aug': 8, 'Sep': 9, 'Oct': 10, 'Nov': 11, 'Dec': 12}
df['Month_num'] = df['Month'].map(month_order)
df['Month_sin'] = np.sin(2 * np.pi * (df['Month_num']-1) / 12)
df['Month_cos'] = np.cos(2 * np.pi * (df['Month_num']-1) / 12)
print(df)

     Date Weekday Month Temperature Humidity Wind   Outlook  Crowdedness  \
0   03-25     Mon   Mar        High      Dry   No     sunny           85   
1   03-26     Tue   Mar         Low    Humid  Yes     rainy           30   
2   03-27     Wed   Mar        High      Dry  Yes  overcast           65   
3   03-28     Thu   Mar     Extreme      Dry  Yes     sunny           45   
4   03-29     Fri   Mar         Low    Humid   No     rainy           25   
5   03-30     Sat   Mar        High    Humid   No  overcast           90   
6   03-31     Sun   Mar        High      Dry  Yes     sunny           95   
7   04-01     Mon   Apr         Low    Humid   No     rainy           35   
8   04-02     Tue   Apr        High      Dry  Yes     sunny           70   
9   04-03     Wed   Apr     Extreme      Dry  Yes  overcast           50   
10  04-04     Thu   Apr        High    Humid   No     sunny           80   
11  04-05     Fri   Apr         Low      Dry  Yes     rainy           45   

    Month_n

df['Month_num'] = df['Month'].map(month_order)

df['Month'] → selects the Month column (e.g., 'Jan', 'Feb')

.map(month_order) → replaces each month with its corresponding number

Result is stored in a new column Month_num

f['Month_num'] = df['Month'].map(month_order)
df['Month'] → selects the Month column (e.g., 'Jan', 'Feb')

.map(month_order) → replaces each month with its corresponding number

Result is stored in a new column Month_num


---
Sine transformation
df['Month_sin'] = np.sin(2 * np.pi * (df['Month_num']-1) / 12)


Let’s break it:

df['Month_num'] - 1

Why subtract 1?

Because months go from 1–12, but for circular math we want them to go from:

0 to 11


So:

Jan (1) → 0

Dec (12) → 11

 / 12

We divide by 12 because there are 12 months in a full cycle.

This converts month position into a fraction of a full cycle.

 2 * np.pi

In trigonometry:

A full circle = 2π radians

So:

2π * (month_position / 12)


Converts the month into an angle on a circle.

 np.sin(...)

Now we take the sine of that angle.

This maps the month onto a circular wave between -1 and 1.


---




**How to Calculate It**

To encode a feature (like Hour) that has a maximum value ($Max$), we use these formulas:$$x = \sin\left(\frac{2 \cdot \pi \cdot \text{Hour}}{\text{Max}}\right)$$$$y = \cos\left(\frac{2 \cdot \pi \cdot \text{Hour}}{\text{Max}}\right)$$Now, Hour 23 and Hour 0 will have $(x, y)$ coordinates that are right next to each other on the circle.

**When to use it?**

Use Cyclic Encoding for anything that "loops":

a. Time: Hours (0–23), Minutes (0–59).

b. Calendar: Days of the week (1–7), Months (1–12).

c. Physics: Compass degrees (0–360°), Angles.

In [ ]:
import numpy as np

# 1. Sample data: Hours of the day
hours = np.array([0, 6, 12, 18, 23])
max_value = 24  # Total hours in a day

# 2. Apply Sine transformation
hour_sin = np.sin(2 * np.pi * hours / max_value)

# 3. Apply Cosine transformation
hour_cos = np.cos(2 * np.pi * hours / max_value)

# Show the results
for h, s, c in zip(hours, hour_sin, hour_cos):
    print(f"Hour {h:2d} -> Sin: {s:6.2f}, Cos: {c:6.2f}")

Hour  0 -> Sin:   0.00, Cos:   1.00
Hour  6 -> Sin:   1.00, Cos:   0.00
Hour 12 -> Sin:   0.00, Cos:  -1.00
Hour 18 -> Sin:  -1.00, Cos:  -0.00
Hour 23 -> Sin:  -0.26, Cos:   0.97


In [ ]:
import numpy as np
import pandas as pd

# Create Sample Data
data = {
    'Size': ['Small', 'Medium', 'Large', 'Medium'],
    'Cuisine': ['Italian', 'Mexican', 'Thai', 'Italian'],
    'City': ['NY', 'LA', 'SF', 'NY'],
    'Hour': [23, 12, 1, 22],
    'Success': [1, 0, 1, 1] # Our Target
}
df = pd.DataFrame(data)

# --- 1. ORDINAL ENCODING (For 'Size') ---
size_map = {'Small': 0, 'Medium': 1, 'Large': 2}
df['Size_Ordinal'] = df['Size'].map(size_map)

# --- 2. LABEL ENCODING (For 'Cuisine') ---
# Simple unique ID assignment
unique_cuisines, df['Cuisine_Label'] = np.unique(df['Cuisine'], return_inverse=True)

# --- 3. ONE-HOT ENCODING (For 'Cuisine') ---
# Creates a column for each type
ohe_cols = pd.get_dummies(df['Cuisine'], prefix='Is')
df = pd.concat([df, ohe_cols], axis=1)

# --- 4. BINARY ENCODING (For 'City') ---
# Convert Label -> Binary String -> Columns
_, city_labels = np.unique(df['City'], return_inverse=True)
df['City_Bin'] = [format(x, '02b') for x in city_labels] # 2-bit binary

# --- 5. TARGET ENCODING (For 'City') ---
# Mean of Success per City
city_means = df.groupby('City')['Success'].mean()
df['City_Target'] = df['City'].map(city_means)

# --- 6. CYCLIC ENCODING (For 'Hour') ---
df['Hour_Sin'] = np.sin(2 * np.pi * df['Hour'] / 24)
df['Hour_Cos'] = np.cos(2 * np.pi * df['Hour'] / 24)

# Display result
print(df.drop(columns=['Success']).to_string())

     Size  Cuisine City  Hour  Size_Ordinal  Cuisine_Label  Is_Italian  Is_Mexican  Is_Thai City_Bin  City_Target      Hour_Sin  Hour_Cos
0   Small  Italian   NY    23             0              0        True       False    False       01          1.0 -2.588190e-01  0.965926
1  Medium  Mexican   LA    12             1              1       False        True    False       00          0.0  1.224647e-16 -1.000000
2   Large     Thai   SF     1             2              2       False       False     True       10          1.0  2.588190e-01  0.965926
3  Medium  Italian   NY    22             1              0        True       False    False       01          1.0 -5.000000e-01  0.866025
